### ISSUE TITLE
LaterBreakspear model not working

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-library#55] opened 2015-11-10 20:07 UTC
Get following error when running region_deterministic_larterbreakspear.ipynb : 

```python
LOG.info("Starting simulation...")
#Perform the simulation
bold_data, bold_time = [], []
tavg_data, tavg_time = [], []
 
for raw, tavg in sim(simulation_length=480000):
    if not raw is None:
        bold_time.append(raw[0])
        bold_data.append(raw[1])
    
    if not tavg is None:
        tavg_time.append(tavg[0])
        tavg_data.append(tavg[1])
 
LOG.info("Finished simulation.")
 


---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-dd04655d51bd> in <module>()
      4 tavg_data, tavg_time = [], []
      5 
----> 6 for raw, tavg in sim(simulation_length=10000):#)480000):
      7     if not raw is None:
      8         bold_time.append(raw[0])

/alexandra/mcintosh_lab/john/Code/libraries_of_others/github/tvb-pack/tvb-library/tvb/simulator/simulator.pyc in __call__(self, simulation_length, random_state)
    477 
    478             # record monitor output & forward to caller
--> 479             output = [monitor.record(step, state) for monitor in self.monitors]
    480             if any(outputi is not None for outputi in output):
    481                 yield output

/alexandra/mcintosh_lab/john/Code/libraries_of_others/github/tvb-pack/tvb-library/tvb/simulator/monitors.pyc in record(self, step, state)
    329         sample = self.sample(step, mt.apply_pre(state))
    330         if sample is not None:
--> 331             return mt.apply_post(sample)
    332 
    333     def sample(self, step, state):

/alexandra/mcintosh_lab/john/Code/libraries_of_others/github/tvb-pack/tvb-library/tvb/simulator/monitors.pyc in apply_post(self, monitor_output, inkey)
    180         ns[ok] = numpy.empty((len(self.post), ) + sample.shape[1:])
    181         for i, expr in enumerate(self.post):
--> 182             ns[inkey] = sample[i]
    183             if len(expr) == 0:
    184                 expr = inkey

IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by JohnGriffiths** [comment] 2015-11-10 20:22
...the problem is in the monitors 'apply_post' method. 

In the error at line 182 above, 

`i` = 1 and `sample.shape` = (1L, 76L, 1L)

So `sample` can only be indexed at `0`. 

Perhaps `sample` needs to be squeezed?

**Comment by maedoc** [comment] 2015-11-11 09:37
Looks like the BOLD monitor is ignored the variables of interest, and only producing one state variable as output.

**Comment by liadomide** [comment] 2015-11-11 10:14
Could it be that this is the same: http://req.thevirtualbrain.org/browse/TVB-1946 ?
If so, the bug was fixed. I just merged on GitHub the latest code with the fix.
Please retry.

**Comment by JohnGriffiths** [comment] 2015-11-11 20:54
So now the code runs, but the `variables_of_interest` does seem to be being ignored; the size of the `TemporalAverage` monitor output is `(#ms, 1, 76, 1)`.

**Comment by JohnGriffiths** [comment] 2015-11-11 22:14
FYI: G2do model sims with the latest code are also ignoring `variables_of_interest`, so this doesn't seem to be specific to LarterBreakspear.

**Comment by liadomide** [comment] 2015-11-11 22:20
No, it doesn't seem to be specific to the model. It is also not linked to recent changes. It looks like an older situation in the BOLD monitor.

**Comment by JohnGriffiths** [comment] 2015-11-11 22:22
Not just the BOLD monitor though; the size of `Raw` and `TemporalAverage` monitors are also not corresponding to `variables_of_interest`

**Comment by maedoc** [comment] 2015-11-13 09:14
The workaround until we fix the bug is to explicitly specific the post expressions on the monitor, see the definition of [`post_expr`](https://github.com/the-virtual-brain/tvb-library/blob/trunk/tvb/simulator/monitors.py#L240) on the base monitor class.

Concretely, if you have 3 variables of interest, try

```python
mons = (TemporalAverage(), ...)
for mon in mons:
    mon.post_expr = 'mon;mon;mon'
```

In a related issue, the BOLD monitor is summing across variables of interest before generating a sample, so we will also fix that at the same time.

**Comment by maedoc** [comment] 2016-02-09 09:54
@JohnGriffiths still having issues with this?

**Comment by JohnGriffiths** [comment] 2016-03-28 21:10
Yes still having issues. Still can't get g2do to give me 2 state variables.  

Seems  that adding in the post_expr as suggested also triggers the evaluation of pre_expr, which then errors.

**Comment by maedoc** [comment] 2016-03-29 07:34
@JohnGriffiths what's your version? git commit or tvb version? If you share your script or minmal reproducer, I'll take a look quickly.

**Comment by JohnGriffiths** [comment] 2016-03-29 17:33
```python
from tvb.simulator.lab import *

conn = connectivity.Connectivity(load_default=True)
mod = models.Generic2dOscillator(variables_of_interest=['V', 'W'])
cpl = coupling.Linear()
solver = integrators.HeunStochastic()
tavgmon = monitors.TemporalAverage()
mons = (tavgmon)
sim = simulator.Simulator(model=mod,connectivity=conn,coupling=cpl,
                          integrator=solver,monitors=mons)
sim.configure()

res = sim.run(simulation_length=50)
t,y = res[0]

```

Note that I am setting variables of interest to return both G2dO state variables. 

Then on the outpu,

`y.shape`

gives 

(51, 1, 76, 1)

...i.e. still only returning the default 1 state variable. 


If as suggested I add in the line 

`tavgmon.post_expr = 'mon;mon;mon' `

I then get error

```python
  File "<string>", line unknown
SyntaxError: '' is not a valid expression
```


This is with the latest github master.

**Comment by maedoc** [comment] 2016-04-05 11:38
@JohnGriffiths thanksfor the example. I'm looking now.

**Comment by maedoc** [comment] 2016-04-05 11:56
At least one error due to a bug in the monitor transforms, you can quickfix at monitors.py:106, 
```python
    def __init__(self, pre_exprs, post_exprs, model_svars=(), delim=';'):
        self.pre = self._prep_exprs(pre_exprs, delim)
        if post_exprs == '':
            post_exprs = delim.join(['mon']*len(self.pre))
        self.post = self._prep_exprs(post_exprs, delim)
```
by adding the 2 lines starting with `if post_exprs`.

I've pushed the changes to SVN if you've got access, otherwise use the quickfix or wait for SVN/Git sync.

I'll try to reproduce the original error, but hopefully this covers it.

**Comment by maedoc** [comment] 2016-04-05 12:05
@JohnGriffiths The Larter-Breakspear demo is running now, so if you still encounter issues (on latest SVN trunk) please reopen the issue here

http://req.thevirtualbrain.org/browse/TVB-2036

**Closed by maedoc** 2016-04-05 12:05 UTC
